### ISSUE TITLE
Insteon scenes as switches

### ISSUE THREAD

**Issue by jonsmirl** [shbatm/hacs-isy994#16]
Why are Insteon scenes represented in HA as switches? This is a source of naming conflict for me since I have scenes and switches that are named the same thing. 

You can send light up/down commands to groups, so shouldn't they be light entities instead of switches? Even better if they were in the own 'scene' namespace.

BTW I have a very large Insteon system, about 180 devices.

**Comment by shbatm** [comment]
Best I can tell (this is a historical issue from long before I started with HA), and from my experience with the Home Assistant Core developers:

1) They shouldn't be lights because you can't provide a brightness value for them. Yes they can be dimmed but only with dim and brighten commands that are handled internally by the insteon devices. (side note: one thing that has not been implemented yet that I'd like to do is to expose more ISY REST commands like dim/brighten/fast on+off as HA Services). 
2) The scene domain is reserved in Home Assistant for Home Assistant scenes and scene engine only. Since the ultimate goal of this component is to be able to be merged into the Core, I don't want to implement anything that would get denied down the road. 
3) Switch was the best choice given the options. 


@overloadut - thoughts on this?

**Comment by jonsmirl** [comment]
Can you create a new HA entity type - 'group' that would correspond to the Insteon scenes?  That would both put them into their own namespace and allow that they have commands that are neither light or switch based - like group dim/brighten/fast on+off.

**Comment by shbatm** [comment]
HA is very prescriptive/restrictive on what integrations can create and how each device is represented. Not going to share my opinions on it here, that's just the way it is (see here if you're interested, https://developers.home-assistant.io/).

If we add the services I mentioned above, that would at least let you use custom button-cards in Lovelace for dim/brighten, and see my post [here](https://community.home-assistant.io/t/isy994-hacs-version-with-pyisy-beta/166897/4) for managing all on and some on.

**Comment by OverloadUT** [comment]
It definitely doesn't make sense (and would be a waste of time as it would be rejected) try to to invent a whole new Home Assistant base entity type just for one component.

It's true that Insteon scenes don't fit super cleanly in to any of the already-defined base types, which speaks to Insteon's uniqueness more than anything else.

Lights and Switches in Home Assistant are only differentiated by dimmability. Insteon Scenes can't be dimmed (not _really_, as shbatm explained) so Switch is the best place for them. (As an aside, Hass `scene` entities have no `turn_off` service, so it wouldn't make sense to use that even if we were allowed)

Adding custom ISY service calls that do Insteon-specific things (incremental dim/fade, etc) is absolutely the way that extra featureset should be exposed, as that's the way it's done for all other components with unique capabilities.

As for the original problem statement of naming conflicts, that's a user-space problem that you'll just need to manage. All Insteon scenes and devices have `unique_ids` so that means you can manage all of their `entity_ids` easily in the Hass interface, so you've got the tools to fix it, even if it's a tad annoying when first setting up new devices or scenes :)

**Comment by bdraco** [comment]
@jonsmirl I worked around this by creating light groups https://www.home-assistant.io/integrations/light.group/
