### ISSUE TITLE
Unable to add new variables as sensors

### ISSUE THREAD

**Issue by Jefe2** [shbatm/hacs-isy994#37]
HACS ISY994 version: 1.2.1
 HA: 107.1
ISY994i: 5.0.16C

After recently adding new variables to ISY994i and setting up configuration.yaml with the new variables (and restarting HA), no new sensors are created for the new variables.  For the past several months I have had 8 ‘variables as sensors’ setup and working flawlessly in HA, but I find I am unable to add new sensors for the new variables.

Is it something I’m doing wrong or a code issue?

**Comment by Jefe2** [comment]
False alarm.  I found the self-inflicted problem.  In addition to having ISY994 installed through HACS, I somehow had (standard) ISY994 installed at the 'Configuration --> Integrations' panel.  Removed the (standard) integration and now things are back to normal.

**Comment by shbatm** [comment]
@Jefe2 Do you (or anyone else using ISY variables in Home Assistant) use anything but the `sensor` platform?

@bdraco -- heads up on this plan too...

I need to make a change to how these are configured to improve compatibility with the config flow and potentially eliminate the need for using the `configuration.yaml` for setup.

The plan is to make variables behave similarly to the `sensor_string` and `ignore` options:
 - The config will have an option for `Sensor Variables String: "ha."` Any variable names containing this string will be added to Home Assistant as as sensor.
 - `switch` and `binary_sensor` will be removed, since those can be modeled using Programs already.
 - Device class, icons and unit of measurement will be set in the device customization within Home Assistant, rather than the config.yaml.

Any objections to this?

**Comment by bdraco** [comment]
Looks good to me.

Ideally we avoid an option to customize the sensor variable string an keep it as HA. to match how everything else works. https://www.home-assistant.io/integrations/isy994/?

One would assume they would only be setup for Home Assistant unless I'm missing a use case.

**Comment by shbatm** [comment]
Just leaving the flexibility there since a lot of the original discussion on the forum was about adding existing variables that were being updated by something else (Program, NodeServer, etc.) and showing them in HA. It's nothing to search for whatever string, so I was planning on just leaving it open if someone is already using a naming convention.

```python
        var_to_add = [
            (vtype, vname, vid)
            for (vtype, vname, vid) in variables.children
            if identifier in vname
        ]
```

**Comment by Jefe2** [comment]
I only use sensors for the isy_variables platform.  Your plan seems solid to me.
Your work on this project is greatly appreciated!
