### ISSUE TITLE
Add set_config_parameter

### ISSUE THREAD

**Issue by MechEng70** [shbatm/hacs-isy994#70]
Can you add this feature to add the set_config_parameter?

Would like to be able to change parameters such as LED color on inovelli and GE switches based on event.  This would also be good to add/delete users from the door locks.

**Comment by shbatm** [comment]
What exactly are you looking to send? Do you know the REST command?

You can send more advanced commands with the `isy994.send_raw_node_command` service and pass things like GV1 GV2 parameters with the `parameters` attribute:

![image](https://user-images.githubusercontent.com/18057952/85209853-da2d5f80-b300-11ea-9010-15964eaf8198.png)

I'm not too keen on going much further down the Z-Wave support rabbit hole right now, since I don't use the ISY for Z-Wave and I'm getting ready to move in the next two months.

**Comment by MechEng70** [comment]
Ok.  I am trying to set the zwave config parameters.  From what I have figured out, the GVX parameters do not set them.  Have tried to set the 13 parameter to 234 on inovelli with out any luck.  If it only accepts GVX objects then that is why.  

Good luck on your move.

**Comment by maverick2041** [comment]
Hi @shbatm I hope your move went well!  I just wanted to add an example REST command that achieves what @MechEng70 is asking here.  I'm using this to set notification color and duration on an Inovelli Red Series Zwave On/Off Switch from the ISY.

http://x.x.x.x/rest/zwave/node/ZW002_1/config/set/8/33884690/4

I'm getting the value for parameter 8 from here: https://nathanfiscus.github.io/inovelli-notification-calc/

**Comment by shbatm** [comment]
Thank you! This is currently on my list for after we get v3 released for
PyISY.

I intended to get that out this week but was called back to work for a
Covid response.

**Comment by maverick2041** [comment]
I deleted my comment after noticing that you already had the relevant examples in your PyISY Issue, but thanks very much for the update.  :)
