### ISSUE TITLE
ISY994 3

### ISSUE THREAD

**Issue by timwing** [shbatm/hacs-isy994#73]
@shbatm, I tried updating to 3.0 and after entering my info to connect, I get "Unexpected error". I have tried just about every combination I can think of but keep getting this same error.

hassio: 0.115.0
device: RPi4

![image](https://user-images.githubusercontent.com/60765858/93541212-c4413200-f923-11ea-947e-283c2b229c52.png)

Logger: homeassistant.components.isy994.config_flow
Source: components/isy994/config_flow.py:90
Integration: Universal Devices ISY994 (documentation, issues)
First occurred: 8:14:55 PM (1 occurrences)
Last logged: 8:14:55 PM

Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/isy994/config_flow.py", line 128, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/usr/src/homeassistant/homeassistant/components/isy994/config_flow.py", line 67, in validate_input
    isy_conf = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/isy994/config_flow.py", line 90, in _fetch_isy_configuration
    isy_conn = Connection(
TypeError: __init__() got an unexpected keyword argument 'log'

**Comment by shbatm** [comment]
Hmm... it looks like it's still trying to load the core `isy994` component instead of the custom one from HACS. 

If you already restarted HASS you may try a full reboot and see if that fixes it; if not you may need to remove and re-add the config entry (possibly with a reboot in between).

**Comment by timwing** [comment]
@shbatm 

But I am trying to load the new one from integrations. The one in HACS says...

⚠️ This integration is for beta testing new features for the ISY994 integration: Home Assistant Core has been updated to include all features that were added in this component's version 1.x.x. Once you have upgraded to Home Assistant >0.110.0, you may safely remove this integration if you do not wish to beta test the new software.

Am I doing this wrong? I also tried a restart of the Pi and it did not help.

**Comment by shbatm** [comment]
> ⚠️ This integration is for beta testing new features for the ISY994 integration: Home Assistant Core has been updated to include all features that were added in this component's version 1.x.x. Once you have upgraded to Home Assistant >0.110.0, you may safely remove this integration if you do not wish to beta test the new software.

That's just the "fair warning" you're going back to testing the beta (HACS) version of the ISY integration.

I can tell it's not loading the right one because of the path in the error you posted:

> File "/usr/src/homeassistant/homeassistant/components/isy994/config_flow.py"

That should be referencing a HACS path, not `homeassistant/components`, since that's the main integration.

Oh, make sure you are not adding the "Discovered" device. I think that only works with the built-in component. Add it through a configuration.yaml file or by searching for the ISY integration in the Add New Integration Menu.

Other than that, if a remove config > restart > re-add config doesn't work I'll have to do some digging. Not sure why it's being stubborn, but I don't have much experience with the Config Entry side.

**Comment by shbatm** [comment]
Cannot replicate this issue. Closing for now. Please re-open if still an issue.
