### ISSUE TITLE
Entity status not updating

### ISSUE THREAD

**Issue by timwing** [shbatm/hacs-isy994#9]
HACS-ISY994: v1.0.12-beta1

All isy-994 entities function from withing hassio but entity status do not update.

Also home-assistant.log shows this for each entity.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 415, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: light.kitchen_lights. Platform isy994 does not generate unique IDs
2020-02-24 17:21:01 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
```

**Comment by shbatm** [comment]
> All isy-994 entities function from withing hassio but entity status do not update.

Should be fixed in `v1.0.14-beta2`.

> Also home-assistant.log shows this for each entity.

You’ll need to clear everything out of .storage/core.restore_states and .storage/core.entity_registry that were added by the test you did with `isy994_2` renaming (it may be easier to delete the two files and let them regenerate, but that will wipe out any customizations you’ve made on the entity_id names).
